new devcontainer based ./bin/dev

diff --git a/bin/dev b/bin/dev
--- a/bin/dev
+++ b/bin/dev
@@ -1,5 +1,52 @@
 #!/usr/bin/env bash
+REPO_ROOT=$(git rev-parse --show-toplevel)
+REL_PATH=$(realpath --relative-to="$REPO_ROOT" "$(pwd)")
+IMAGE="ghcr.io/dimensionalos/dev"
+IMAGE_NAME="$IMAGE:dev"
 
+image_exists() {
+    docker image inspect "${IMAGE_NAME}" &>/dev/null
+}
+
+image_pull() {
+    docker pull "$IMAGE_NAME"
+}
+
+ensure_image_downloaded() {
+    if ! image_exists "$1"; then
+        echo "Image ${IMAGE_NAME} not found. Pulling..."
+        image_pull "$1"
+    fi
+}
+
+check_image_running() {
+    if docker ps -q --filter "ancestor=${IMAGE_NAME}" | grep -q .; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+stop_image() {
+    if check_image_running ${IMAGE_NAME}; then
+        echo "Stopping containers from image ${IMAGE_NAME}..."
+        docker stop $(docker ps -q --filter "ancestor=${IMAGE_NAME}")
+    else
+        echo "No containers from image ${IMAGE_NAME} are running."
+    fi
+}
+
+
+ensure_image_running() {
+    ensure_image_downloaded
+
+    if check_image_running ${IMAGE_NAME}; then
+        return
+    else
+        echo "Starting container from image ${IMAGE_NAME}..."
+        devcontainer up --workspace-folder "$REPO_ROOT"
+    fi
+}
 
 get_tag() {
     local branch_name
@@ -16,9 +63,6 @@ get_tag() {
             | sed -E 's#^-+|-+$##g')
         ;;
     esac
-#    echo "image tag determined: '${image_tag}'"
-    
-    # Return the image tag value
     echo "${image_tag}"
 }
 
@@ -38,47 +82,52 @@ remove_image() {
     docker rm -f "dimos-dev-${tag}" 2>/dev/null || true
 }
 
-COMPOSE_FILE="docker/dev/docker-compose.yaml"
+ensure_devcontainer_installed() {
+    command -v devcontainer &>/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo "devcontainer CLI is not installed. Installing..."
+        sudo npm install -g @devcontainers/cli
+    fi
+    command -v devcontainer &>/dev/null
+    if [[ $? -ne 0 ]]; then
+        echo "Failed to install devcontainer CLI. Please install it manually."
+        exit 1
+    fi
+}
 
-# Parse flags and commands
-while [[ $# -gt 0 ]]; do
+# Passes all arguments to devcontainer command, ensuring:
+# - devcontainer CLI is installed
+# - the image is running
+# - the workspace folder is set to the repository root
+run_devcontainer() {
+    ensure_devcontainer_installed
+    ensure_image_running
+    devcontainer $1 --workspace-folder "$REPO_ROOT" "${@:2}"
+}
+
+if [[ $# -eq 0 ]]; then
+    run_devcontainer exec bash
+else
     case "$1" in
-        -c|--cuda)
-            COMPOSE_FILE="docker/dev/docker-compose-cuda.yaml"
-            shift
-            ;;
-        remove)
-            remove_image
-            exit 0
-            ;;
         build)
-            remove_image
             build_image
             shift
             ;;
-        *)
-            # Skip unrecognized args
+        stop)
+            stop_image
             shift
             ;;
+        down)
+            stop_image
+            shift
+            ;;
+        pull)
+            docker pull ghcr.io/dimensionalos/dev:dev
+            shift
+            ;;
+        *)
+            run_devcontainer "$@"
+            shift
+          ;;
     esac
-done
-
-image_tag=$(get_tag)
-image_name="ghcr.io/dimensionalos/dev:${image_tag}"
-
-if ! docker image inspect "${image_name}" &>/dev/null; then
-    echo "Image ${image_name} not found. Building..."
-    build_image
 fi
-
-# Get current directory relative to repo root
-REPO_ROOT=$(git rev-parse --show-toplevel)
-REL_PATH=$(realpath --relative-to="$REPO_ROOT" "$(pwd)")
-
-export DEV_IMAGE_TAG="${image_tag}"
-echo "Starting container with image: ghcr.io/dimensionalos/dev:${image_tag}"
-docker compose -f "$REPO_ROOT/$COMPOSE_FILE" up -d
-
-container_name="dimos-dev-${image_tag}"
-echo "Entering container $container_name"
-docker exec -it "$container_name" bash -c "cd $REL_PATH; exec bash"
